### ISSUE TITLE
TypeError: 'AnonymousUser' object is not iterable

### ISSUE THREAD

**Issue by Forchapeatl** [haasr/collaborative-blog#2]
The comment system is not working for anonymous user. Please how do I get anonymous  user comments working

**Comment by haasr** [comment]
Hello,

Could you provide more information? I.e., walk me through the steps you took to reproduce the error and provide a stack trace. Relevant screenshots would also be appreciated.

**Comment by haasr** [comment]
I think I have resolved the issue you are having in my last commit. I was doing a bad check to see if the user was authenticated (I really need unit tests 🤦). Please pull down and see if that resolved your issue.

**Comment by Forchapeatl** [comment]
![image](https://user-images.githubusercontent.com/24577149/193817759-008e872c-95cf-4522-a1c9-06dae76d80d9.png)

Please a new error has poped up. Please for directions on how I could help you resolve this

**Comment by haasr** [comment]
That should be `request.user.id`

![image](https://user-images.githubusercontent.com/49294304/194988959-07e00a67-c88e-40d9-862f-20a2b9331239.png)

Make sure you run `git pull` on the server end and restart gunicorn (`sudo systemctl restart gunicorn`) if it is running with gunicorn.

**Comment by Forchapeatl** [comment]
thank you

**Comment by haasr** [comment]
Of course, Forcha. Is it working as expected now?

**Comment by Forchapeatl** [comment]
![image](https://user-images.githubusercontent.com/24577149/196698251-ea3a5870-b242-4ea9-8da7-20271f9b40f2.png)

Thank you @haasr .
